-- MySQL Script generated by MySQL Workbench
-- Mon Feb 23 08:46:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

- -----------------------------------------------------
-- Schema campeoes_f1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `campeoes_f1` ;

-- -----------------------------------------------------
-- Schema campeoes_f1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campeoes_f1` DEFAULT CHARACTER SET utf8mb3 ;

USE `campeoes_f1` ;

-- -----------------------------------------------------
-- Table `campeoes_f1`.`equipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeoes_f1`.`equipes` ;

CREATE TABLE IF NOT EXISTS `campeoes_f1`.`equipes` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_equipe`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `campeoes_f1`.`pilotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeoes_f1`.`pilotos` ;

CREATE TABLE IF NOT EXISTS `campeoes_f1`.`pilotos` (
  `id_piloto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_piloto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `campeoes_f1`.`temporadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeoes_f1`.`temporadas` ;

CREATE TABLE IF NOT EXISTS `campeoes_f1`.`temporadas` (
  `id_temporada` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NOT NULL,
  PRIMARY KEY (`id_temporada`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `campeoes_f1`.`campeonatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeoes_f1`.`campeonatos` ;

CREATE TABLE IF NOT EXISTS `campeoes_f1`.`campeonatos` (
  `id_campeonato` INT NOT NULL AUTO_INCREMENT,
  `pilotos_id_piloto` INT NOT NULL,
  `equipes_id_equipe` INT NOT NULL,
  `temporadas_id_temporada` INT NOT NULL,
  PRIMARY KEY (`id_campeonato`),
  INDEX `fk_campeonatos_pilotos_idx` (`pilotos_id_piloto` ASC) VISIBLE,
  INDEX `fk_campeonatos_equipes1_idx` (`equipes_id_equipe` ASC) VISIBLE,
  INDEX `fk_campeonatos_temporadas1_idx` (`temporadas_id_temporada` ASC) VISIBLE,
  CONSTRAINT `fk_campeonatos_equipes1`
    FOREIGN KEY (`equipes_id_equipe`)
    REFERENCES `campeoes_f1`.`equipes` (`id_equipe`),
  CONSTRAINT `fk_campeonatos_pilotos`
    FOREIGN KEY (`pilotos_id_piloto`)
    REFERENCES `campeoes_f1`.`pilotos` (`id_piloto`),
  CONSTRAINT `fk_campeonatos_temporadas1`
    FOREIGN KEY (`temporadas_id_temporada`)
    REFERENCES `campeoes_f1`.`temporadas` (`id_temporada`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
